# Generated by Django 2.1.7 on 2019-03-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20190309_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
