# Generated by Django 2.1.7 on 2019-03-18 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20190318_1456'),
        ('appointment', '0006_appointment_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Doctor')),
            ],
            options={
                'verbose_name_plural': 'availabilities',
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='appointment.Availability')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaiable_from', models.TimeField(verbose_name='Appointment time slot')),
                ('avaiable_to', models.TimeField(verbose_name='Appointment time ends')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='token_no',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Waiting')], default=3, null=True),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='appointment.TimeSlot'),
        ),
        migrations.AddField(
            model_name='availability',
            name='time_slot',
            field=models.ManyToManyField(related_name='available', through='appointment.AvailableTime', to='appointment.TimeSlot'),
        ),
    ]
