# Generated by Django 2.1.7 on 2019-03-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20190318_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot_from',
        ),
    ]
