# Generated by Django 2.1.7 on 2019-03-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_remove_appointment_time_slot_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='avaiable_from',
            new_name='available_from',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='avaiable_to',
            new_name='available_to',
        ),
    ]
