# Generated by Django 2.1.7 on 2019-03-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_remove_appointment_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Waiting')], default=3),
        ),
    ]
