# Generated by Django 2.1.7 on 2019-04-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.TimeSlot'),
        ),
    ]
