# Generated by Django 2.2 on 2019-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20190415_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_no',
            field=models.IntegerField(default=0),
        ),
    ]
