# Generated by Django 2.2 on 2019-04-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_remove_appointment_appointment_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment_date',
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment'),
            preserve_default=False,
        ),
    ]
