# Generated by Django 2.1.7 on 2019-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(to='hospital.Department'),
        ),
    ]
