# Generated by Django 2.1.7 on 2019-03-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_post',
            old_name='author',
            new_name='user',
        ),
    ]
