# Generated by Django 2.1.7 on 2019-03-18 09:11

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
